# Site settings
title: Magnus Landén | Dev
description: Magnus Landén | Dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://magnuslanden.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Magnus Landén
user_description: System/ Web developer
user_title: Web Developer
email: magnus.landen@hotmail.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: test
    url: /test

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
